<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */


class pometaImagesSettings {
	private $pImages_options;


    var $thumbnail_sizes=false;


	public function __construct() {
		add_action( 'admin_menu', array( $this, 'pImages_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'pImages_page_init' ) );


        $this->thumbnail_sizes=false;
	}

	public function pImages_add_plugin_page() {
		add_options_page(
			'Pometa Imágenes', // page_title
			'Imágenes', // menu_title
			'manage_options', // capability
			'pimages', // menu_slug
			array( $this, 'pImages_create_admin_page' ) // function
		);
	}

	public function pImages_create_admin_page() {
		    $this->pImages_options = get_option( 'pImages_settings' ); ?>
			<style type="text/css">
				input[type=date], input[type=datetime-local], input[type=datetime],  input[type=float], input[type=email], input[type=month], input[type=number], input[type=password], input[type=search], input[type=tel], input[type=text], input[type=time], input[type=url], input[type=week] {padding: 0 8px; line-height: 2; min-height: 30px;}
				input[type=color], input[type=date], input[type=datetime-local], input[type=float], input[type=datetime], input[type=email], input[type=month], input[type=number], input[type=password], input[type=search], input[type=tel], input[type=text], input[type=time], input[type=url], input[type=week], select, textarea {box-shadow: 0 0 0 transparent;border-radius: 4px;border: 1px solid #7e8993; background-color: #fff; color: #32373c;}

                table.pimages-table th {border: 1px solid black;}
                table.pimages-table td, table.pimages-table th {padding: 5px;text-align: center;width:50px;}
                table.pimages-table {width: auto;}
                .size-add-format{display:flex;flex-direction:column;}
                .size-add-format > div.row {flex:1;display:flex;}
                .size-add-format > div.row > div {flex:0 0 80px;max-width:80px;padding:5px;margin:2px;text-align:center;}
                .size-add-format > div.row > div input {max-width:100%;}


    	</style>
		<div class="wrap">
			<h2>Pometa Images</h2>
			<p>Configuració de pometaImages.</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'pImages_option_group' );
					do_settings_sections( 'pimages-admin' );
					submit_button();
				?>
			</form>

		</div>
	<?php }

	public function pImages_page_init() {
		register_setting(
			'pImages_option_group', // option_group
			'pImages_settings', // option_name
			array( $this, 'pImages_sanitize' ) // sanitize_callback
		);


		add_settings_section(
			'pImages_setting_formats', // id
			'<hr><br>'.__("Formats d'imatges de la web:","pimagesltd"), // title
			array( $this, 'pImages_section_formats' ), // callback
			'pimages-admin' // page
		);


		add_settings_field(
			'formats_list', // id
			'Formats actuals', // title
			array( $this, 'formats_inici_callback' ), // callback
			'pimages-admin', // page
			'pImages_setting_formats' // section
		);

/*-
		add_settings_field(
			'formats_add', // id
			'Afegir nou format', // title
			array( $this, 'formats_add_callback' ), // callback
			'pimages-admin', // page
			'pImages_setting_formats' // section
		);
-*/
		


	}

	public function pImages_sanitize($input) {

        $sanitary_values=$input;
		return $sanitary_values;
	}

    
	public function pImages_section_formats() {
				echo "<p>Per defecte Wordpress inclou formats d'imatges. El tema també pot afegir altres formats disponbiles. En aquesta partat també podràs incloure més formats a medida.</p>";
	}

    
	public function data_final_callback() {
		printf(
			'<input class="regular-text" type="date" name="pImages_settings[data_final]" id="data_final" value="%s">',
			isset( $this->pImages_options['data_final'] ) ? esc_attr( $this->pImages_options['data_final']) : ''
		);
	}
    public function formats_add_callback() {


        echo '
            
            <div class="size-add-format">
                <div class="row">
                        <div class="name">
                            <strong>'.__("Alias","pimagesltd").'</strong>
                        </div>
                        <div class="width">
                        <strong>'.__("Width","pimagesltd").'</strong>
                        </div>
                        <div class="height">
                        <strong>'.__("Height","pimagesltd").'</strong>
                        </div>
                        <div class="crop">
                        <strong>'.__("Crop","pimagesltd").'</strong>
                        </div>
                        <div class="webp">
                        <strong>'.__("WebP","pimagesltd").'</strong>
                        </div>
                        <div class="enabled">
                        <strong>'.__("Enabled","pimagesltd").'</strong>
                        </div>
                </div>
                <div class="row body">
                    <div class="name">
                        <input type="text" name="size-add-name" id="size-add-name">
                    </div>
                    <div class="width">
                        <input type="number" step=1 name="  size-add-width" id="size-add-width">
                    </div>
                    <div class="height">
                        <input type="number" step=1 name="size-add-height" id="size-add-height">
                    </div>
                    <div class="crop">
                        <input type="checkbox" name="size-add-crop" id="size-add-crop">
                    </div>
                    <div class="webp">
                        <input type="checkbox" name="size-add-webp" id="size-add-webp" checked="checked">
                    </div>
                    <div class="enabled">
                        <input type="checkbox" name="size-add-enabled" id="size-add-enabled" checked="checked">
                    </div>
                </div>
            </div>
        ';
    }

    function get_thumbnail_formats() {

        
        if ( $this->thumbnail_sizes === false ) {

            $this->thumbnail_sizes = pImages_get_intermediate_sizes();

        }
        return $this->thumbnail_sizes;
    }

    public function formats_inici_callback() {

		$thumbnail_sizes = $this->get_thumbnail_formats();

        echo '<table class="pimages-table striped table-view-list wp-list-table">';
        echo '
            <thead>
                <tr>
                    <th class="pimages-column-id">Id</th>
                    <th class="pimages-column-id">Name</th>
                    <th class="pimages-column-id">Width</th>
                    <th class="pimages-column-id">Height</th>
                    <th class="pimages-column-id">Crop</th>
                    <th class="pimages-column-id">WebP</th>
                </tr>
            </thead>
        ';
        echo '
            <tbody>
        ';
        $n=0;
        foreach($thumbnail_sizes as $size_id => $size_data) {
            $n++;
            $name = $size_id;
            $width = get_array_value($size_data,"width",0);
            $height = get_array_value($size_data,"height",0);
            $crop = get_array_value($size_data,"crop",false);

            $webp_state = get_array_value(get_array_value(get_array_value($this->pImages_options,"size",array()),$size_id,array()),"webp","off");
            $webp = '<input type="checkbox" name="pImages_settings[size]['.$name.'][webp]" '.($webp_state=="on"?'checked="checked"':'').'>';

            echo '
                <tr>
                    <td class="pimages-column-id">'.$n.'</td>
                    <td class="pimages-column-id">'.$name.'</td>
                    <td class="pimages-column-id">'.$width.'</td>
                    <td class="pimages-column-id">'.$height.'</td>
                    <td class="pimages-column-id">'.($crop? "√" : "").'</td>
                    <td class="pimages-column-id">'.$webp.'</td>
                </tr>
            ';
        }
        echo '
            </tbody>'
        ;
        echo '</table>';
        
        
    }

    
}
if ( is_admin() ) $pImagesSettings = new pometaImagesSettings();

/*
 * Retrieve this value with:
 * $pImages_options = get_option( 'pImages_settings' ); // Array of All Options
 * $data_final = $pImages_options['data_final']; // Data de finalització de cursos
 * $preu_2cursos = $pImages_options['preu_2cursos']; // Preu \"2Cursos\"
 * $preu_3cursos = $pImages_options['preu_3cursos']; // Preu \"3Cursos\"
 * $preu_2cursos_tutoria = $pImages_options['preu_2cursos_tutoria']; // Preu \"2Cursos+TUTORIA\"
 * $preu_3cursos_tutoria = $pImages_options['preu_3cursos_tutoria']; // Preu \"3Cursos+TUTORIA\"
 */

function pImages_settings_get() {
		 $pImages_options = get_option( 'pImages_settings' ); // Array of All Options
		return $pImages_options;
}

function pImages_settings_get_option($option,$default=false) {
		$settings = pImages_settings_get();
		return get_array_value($settings,$option,$default);
}

function pImages_settings_get_periodo_date() {
		return pImages_settings_get_option("data_final","");
}


function pImages_get_intermediate_sizes() {


    global $_wp_additional_image_sizes;
    $sizes=array();

    foreach ( get_intermediate_image_sizes() as $size ) {
        $sizes[ $size ]['label'] = $size;
        if ( in_array( $size, array( 'thumbnail', 'medium', 'medium_large', 'large' ) ) ) {
            $sizes[ $size ]['width']  = (int) get_option( $size . '_size_w' );
            $sizes[ $size ]['height'] = (int) get_option( $size . '_size_h' );
            $sizes[ $size ]['crop']   = ( 'thumbnail' == $size ) ? (bool) get_option( 'thumbnail_crop' ) : false;
        } elseif ( ! empty( $_wp_additional_image_sizes ) && ! empty( $_wp_additional_image_sizes[ $size ] ) ) {
            $sizes[ $size ]['width']  = (int) $_wp_additional_image_sizes[ $size ]['width'];
            $sizes[ $size ]['height'] = (int) $_wp_additional_image_sizes[ $size ]['height'];
            $sizes[ $size ]['crop']   = (bool) $_wp_additional_image_sizes[ $size ]['crop'];
        }
    }

    return $sizes;
}




